### ISSUE TITLE
Edit code Maven issue

### ISSUE THREAD

**Issue by Triton-oidc** [FrankGasparovic/Windows-Desktop-SSO-Node#1]
Hi,
it works great on our Forgerock AM, I'd like to do a modification, but when i import the maven project, i got dependency issues.
I saw a "forgerock-private-releases" in the pom.xml file
Does it mean that i need some specific credentials do to a modification ?
Some colleague of mine may have access to that kind of credentials.
Thanks for any help

**Comment by FrankGasparovic** [comment]
Hi there,

Are you an existing ForgeRock customer or partner? If so, you log in to backstage.forgerock.com and follow this guide which outlines how to setup your settings.xml file to pull down the necessary files from our private repo: https://backstage.forgerock.com/knowledge/kb/article/a74096897

Thanks,

Frank

**Comment by Triton-oidc** [comment]
Perfect, that's the answer i was looking for. I'll ask my colleague who must have the credentials somewhere.
Thanks
